export const ORDER_STATUSES = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PENDING_STORE: "PENDING_STORE",
  PREPARING: "PREPARING",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  NEW: "NEW",
  ACCEPTED: "ACCEPTED",
  READY: "READY",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
} as const;

export type OrderStatus = (typeof ORDER_STATUSES)[keyof typeof ORDER_STATUSES];

// These statuses mean the order has moved beyond payment-pending verification.
export const FINAL_ORDER_STATUSES: OrderStatus[] = [
  ORDER_STATUSES.NEW,
  ORDER_STATUSES.PENDING_STORE,
  ORDER_STATUSES.ACCEPTED,
  ORDER_STATUSES.PREPARING,
  ORDER_STATUSES.READY,
  ORDER_STATUSES.READY_FOR_PICKUP,
  ORDER_STATUSES.OUT_FOR_DELIVERY,
  ORDER_STATUSES.COMPLETED,
  ORDER_STATUSES.CANCELLED,
  ORDER_STATUSES.FAILED,
];
