export const ORDER_STATUSES = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  NEW: "NEW",
  ACCEPTED: "ACCEPTED",
  READY: "READY",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  FAILED: "FAILED",
} as const;

export type OrderStatus = (typeof ORDER_STATUSES)[keyof typeof ORDER_STATUSES];

export const FINAL_ORDER_STATUSES: OrderStatus[] = [
  ORDER_STATUSES.NEW,
  ORDER_STATUSES.ACCEPTED,
  ORDER_STATUSES.READY,
  ORDER_STATUSES.COMPLETED,
  ORDER_STATUSES.CANCELLED,
  ORDER_STATUSES.FAILED,
];
